/**
 * Unit tests for kalmanExpenditure.ts
 *
 * A 2-state linear Kalman filter (trend weight + TDEE) that back-solves
 * expenditure from calorie intake (control input) and scale weight (measurement).
 * Prototype only — not wired into production.
 */

import {
  initKalmanState,
  kalmanPredict,
  kalmanUpdate,
  runKalmanFilter,
  DEFAULT_KALMAN_PARAMS,
  type KalmanState,
} from '@/lib/kalmanExpenditure';

const ENERGY_DENSITY = DEFAULT_KALMAN_PARAMS.energyDensity; // 7700

describe('kalmanExpenditure', () => {
  describe('kalmanPredict', () => {
    it('leaves the TDEE mean unchanged (random walk) but moves weight by the energy balance', () => {
      const state = initKalmanState(80, 2500);
      const next = kalmanPredict(state, 2000, DEFAULT_KALMAN_PARAMS);

      // E is a random walk: predict does not change its mean
      expect(next.tdee).toBeCloseTo(2500, 6);
      // W_next = W + (intake - E) / rho = 80 + (2000 - 2500) / 7700
      expect(next.weightKg).toBeCloseTo(80 + (2000 - 2500) / ENERGY_DENSITY, 6);
    });

    it('grows the TDEE uncertainty (predict adds process noise)', () => {
      const state = initKalmanState(80, 2500);
      const next = kalmanPredict(state, 2000, DEFAULT_KALMAN_PARAMS);

      expect(next.covariance[1][1]).toBeGreaterThan(state.covariance[1][1]);
    });
  });

  describe('kalmanUpdate', () => {
    it('shrinks TDEE uncertainty when a weight measurement arrives', () => {
      const predicted = kalmanPredict(initKalmanState(80, 2500), 2000, DEFAULT_KALMAN_PARAMS);
      const updated = kalmanUpdate(predicted, predicted.weightKg, DEFAULT_KALMAN_PARAMS);

      expect(updated.covariance[1][1]).toBeLessThan(predicted.covariance[1][1]);
    });
  });

  describe('runKalmanFilter', () => {
    it('converges toward the true TDEE from a wrong initial guess', () => {
      // Ground truth: TDEE 2500, eating 2000 -> 500 kcal/day deficit.
      // Clean, noiseless weight series generated by the same energy balance.
      const trueTdee = 2500;
      const intake = 2000;
      const days: { intakeKcal: number | null; weightKg: number | null }[] = [];
      let w = 80;
      for (let i = 0; i < 180; i++) {
        days.push({ intakeKcal: intake, weightKg: w });
        w = w + (intake - trueTdee) / ENERGY_DENSITY;
      }

      // Start with a deliberately wrong guess of 3000 kcal.
      const states = runKalmanFilter(days, DEFAULT_KALMAN_PARAMS, 3000);
      const final = states[states.length - 1];

      expect(states).toHaveLength(days.length);
      expect(Math.abs(final.tdee - trueTdee)).toBeLessThan(150);
    });

    it('holds the estimate across a missing weigh-in (predict only, uncertainty grows)', () => {
      const days: { intakeKcal: number | null; weightKg: number | null }[] = [
        { intakeKcal: 2000, weightKg: 80 },
        { intakeKcal: 2000, weightKg: null }, // missing weigh-in
      ];
      const states = runKalmanFilter(days, DEFAULT_KALMAN_PARAMS, 2500);

      const afterInit = states[0];
      const afterMissing = states[1];
      // No measurement to correct against -> TDEE uncertainty should be larger.
      expect(afterMissing.covariance[1][1]).toBeGreaterThan(afterInit.covariance[1][1]);
    });
  });
});
